# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f8058f36764eab2f0176aeacacc5add52e9b5aa4d0abfe564973b909385ba9c4ba7e2a52b27b7e06ab694162236677e83f46d85eb9293b954bf158a1b2bd270

test:
  secret_key_base: 471337c1ca93db61c75ea62430e65a52715fc1ab3865b7817caafb8dcad75bbd10ff0d8afda03bfb4f8ad524103c6242a3222b26dea3747476ae48f37d70caa9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
